import type { Metadata } from "next";
import "./globals.css";
import React from "react";

export const metadata: Metadata = {
  title: "Forum App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-100 min-h-screen flex flex-col">
        <header className="bg-gray-800 text-white p-4 shadow-md">
          <div className="container mx-auto flex justify-between items-center">
            <h1 className="text-2xl font-bold">Forum App</h1>
          </div>
        </header>
        <main className="container mx-auto p-6 flex-1">{children}</main>
        <footer className="bg-gray-800 text-white text-center py-4">
          © 2024 Forum App. All Rights Reserved.
        </footer>
      </body>
    </html>
  );
}
