server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:env/local.env[.properties]
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/forum
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security.oauth2.server.resource: TRACE