server:
  port: 8081

spring:
  config:
    activate:
      on-profile: local
    import:
      - optional:file:env/local.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}
          jwk-set-uri: ${KEYCLOAK_HOST}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/forum
    username: season
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        time_zone: UTC
        default_schema: public

logging:
  level:
    org:
      springframework:
        security: DEBUG